### ISSUE TITLE
Using Mailpie instead of Roundcube

### ISSUE THREAD

**Issue by jalcine** [al3x/sovereign#350]
I know it's still in beta, and this is actually more so of a gauge of interest but how interesting would it be having [Mailpie](https://www.mailpile.is/) instead of Roundcube?

**Comment by al3x** [comment]
Mailpile has been discussed in previous issues. I'm open to it, and I appreciate the project's focus on privacy. However, because Sovereign is intended to provide a reliable personal cloud and not an experimental playground, we've tried to only use well-tested software for critical services like email.
