### ISSUE TITLE
Apache -> Nginx?

### ISSUE THREAD

**Issue by al3x** [al3x/sovereign#42]
Several people have inquired about using Nginx, as it's lighter-weight than Apache. I'm open to the idea.

[This Nginx config](https://gist.github.com/konklone/6532544) has some nice features, particularly when it comes to SSL, and could be used as a base template.

**Comment by al3x** [comment]
Not to sound like a broken record, but: I'm open to a pull request. Apache httpd has worked well for most Sovereign users. As @ariddell pointed out, higher-memory VPS instances have come down in price.

**Comment by aminb** [comment]
I'm curious to know what people think of switching from Apache to Nginx, more than a year later after the last comment on this issue.

It was mentioned in the LetsEncrypt discussion over at #451, and also with PR #526 aiming to modularize sovereign I thought it might be a good time to give this a second thought.

From what I've gathered, @ariddell is in favor of switching to Nginx, and @neuhaus doesn't mind it.

I'd like to see what everyone thinks of this.

P.S. I'm using Nginx on my server (along with owncloud) and can probably help with some of the virtual host files.

**Comment by carljm** [comment]
I'm in favor. I prefer nginx to Apache; this was one thing that made me debate using sovereign vs rolling my own solution.

**Comment by jplock** [comment]
I'm in favor of switching to nginx.

**Comment by TotallyInformation** [comment]
Agreed, NGINX is technically superior in most parts and certainly less resource hungry. Even if VPS memory costs are coming down, there is still never enough since we always want to do more with them!

**Comment by tynsh** [comment]
In January I've played around with porting the apace configs to nginx on a freshly installed server with the jessie-playbooks and have got a working set now, but I currently don't have time to put those configs into the playbook. Testing is a pain when jessie isn't fully supported yet. I'd wait until the jessie transition is finished and put them into the playbook afterwards.

**Comment by alexanderadam** [comment]
@tynsh do you have any fork or something were we could support you somehow?

**Comment by tynsh** [comment]
Unfortunately I've lost that config when I've wiped my server without having a backup :-(

Since I no longer use sovereign I doubt I will try again, sorry.

**Comment by alexanderadam** [comment]
@tynsh what a pity. If I may ask: do you use an alternative you could recommend?

**Comment by tynsh** [comment]
@alexanderadam yes, I've started writing my own playbook which uses [a nginx role](https://github.com/HanXHX/ansible-nginx) which is pretty easy to use and works well. I can recommend that if you want to integrate nginx into your playbooks.

**Comment by alexanderadam** [comment]
@tynsh does it integrate a full email config similar to the one in [sovereign](https://github.com/sovereign/sovereign#services-provided) as well? You don't [have it public on GitHub yet](https://github.com/tynsh?tab=repositories), right?

**Comment by tynsh** [comment]
ah, well, the email config is not yet there. I wasn't thinking of uploading the playbook since it is written quite messy. I will see if I can clean it up and upload it but don't expect it to happen in the near future. Even if it will be uploaded I doubt you will be able to use it as a replacement for sovereign since it heavily relies on [zerotier](https://www.zerotier.com/) and spreads the configuration on multiple servers.

**Comment by alexanderadam** [comment]
@al3x I totally understand that there are reasons for you not to solve this issue not by yourself.

However, if I interpreted your comment correctly, *closing* this issue was not what you really intended to do. Because you are actually *open* to get this issue solved. So as this issue *isn't rejected nor solved* it should be still open so nobody can misinterpret the state of this issue (as rejected or closed).

PS: independent from that I just wanted to mention that it's absolutely awesome what you've done

**Comment by aminb** [comment]
For others interested in an alternative to some of Sovereign's functionality (mail, calendar and contacts), I'd recommend taking a look at [Mailu](https://github.com/Mailu/Mailu), which I've been happily using for a few months now and haven't had any issues with it.

**Comment by Brando753** [comment]
Whats the status on this, is there a reason it was closed? It seems there is still a desire by users for nginx over apache. @aminb as for Mailu if that was a set of ansible scripts instead of a docker container I would  easily consider using it.
